### ISSUE TITLE
Evil People

### ISSUE THREAD

**Issue by GJzilla** [MystenLabs/mysten-app-docs#47]
Tranaction Hash:
0x2810ae974c7e3a34077f155841a081a01c94f61bec09e8d23c99450cb6a5f605

Wallet#2
0x8b9dff0de4a3f9616035618be80cbaaf3dae57486b47fdc0d7bdface1c75f446

Wallet #1 
0x87e3f9509aa346e351ccb85a45ccbde3391cdf51c970716419c5a30975c62cc4

Stole my money right out of my SuiWallet by transferring my money to them. 
They claimed moderator of Cetus Protocol discord and modified all the webpage information to hide their actions. They changed every interaction to look legit and steal people's information. Somehow they just keep changing identity and siphoning money. 
You can clearly see I DID NOT SEND THEM THAT MONEY. Please work with me to return my money.  

https://suivision.xyz/account/0x87e3f9509aa346e351ccb85a45ccbde3391cdf51c970716419c5a30975c62cc4

**Comment by thava-k** [comment]
How was this resolved? This is worrying.
